#pragma once

#include "config_common.h"

/* key matrix size */
#define MATRIX_ROWS 10
#define MATRIX_COLS 8

#define MATRIX_ROW_PINS { B3, B2, B1, B0, C6, B6, B5, B4, D7, D6 }
#define MATRIX_COL_PINS { E6, F0, F1, F4, F5, F6, F7, C7 }
#define UNUSED_PINS { D5, D4, D2, B7 }

#define DIODE_DIRECTION COL2ROW
#define RGB_DI_PIN D3

#define RGBLED_NUM 16

#define RGBLIGHT_ANIMATIONS	
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_BREATHING	
#define RGBLIGHT_EFFECT_CHRISTMAS	
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_TWINKLE

#define RGBLIGHT_LIMIT_VAL 125
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_STATIC_LIGHT	  
#define RGBLIGHT_DEFAULT_HUE 0